tighterror: use `root-level` term instead of `top-level`
This commit adjusts the documentation and implementation to use the term
`root-level` instead of `top-level`. This is done because IMO the new
term better describes what is being meant, the root of specification
file.