tighterror: update documentation
This commit updates the documentation following commit 84d1caf. The
binary layout of error-kind was updated to make category bits more
significant. This commit updates the binary layout diagrams accordingly.