tb: fix `clippy::manual_inspect` error
Otherwise clippy fails in the new v1.81.0-beta.1 version with error [1].

The MSRV is bumped to v1.76 because `Result::inspect_err` is available
only since this version.

[1]

error: using `map_err` over `inspect_err`
   --> crates/tighterror-build/src/coder/generator/bits.rs:31:60
    |
31  |         let repr_type = ReprType::from_n_bits(n_kind_bits).map_err(|e| {
    |                                                            ^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_inspect
note: the lint level is defined here
   --> crates/tighterror-build/src/lib.rs:122:9
    |
122 | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(clippy::manual_inspect)]` implied by `#[deny(warnings)]`
help: try
    |
31  ~         let repr_type = ReprType::from_n_bits(n_kind_bits).inspect_err(|e| {
32  |             let ltn = ReprType::largest_type_name();
33  |             log::error!(
34  |                 "not enough bits in largest supported underlying type {ltn}: {n_kind_bits}"
35  ~             );
    |

error: could not compile `tighterror-build` (lib) due to 1 previous error