tighterror: update documentation for error name casing
This commit updates the documentation following the change of error
names' casing from UpperCamel to UpperSnake.