tighterror: add the accompanying crates skeleton
Note that Cargo.lock as removed from .gitignore, as it is required for
the `cargo-tighterror` crate, which is a binary.