tighterror: cleanup the interface traits
This commit renames the assoriated types of public traits to have a
shorter and cleaner API. Specifically, the word Type is removed from
the types names. ReprType is renamed to simply R.