tighterror: represent paths with PathBuf instead of String
There are two advantages to this approach:

- no need to convert paths to String. So there is no need for the
  BAD_PATH error.
- support non-unicode characters that are allowed on some operating
  systems.