tb: enable *separate files* mode in `multiple_modules` test
This commit enables *separate files* mode for coverage in the main
multiple-modules test.

Note that `doc` arrtributes were removed from the module specification.
This is because of error [1]. It seems to be a limitation of the
`std::include` macro to fail to parse the inner-comment of the generated
module.

[1]

error[E0753]: expected outer doc comment
 --> /home/rafa/work/tighterror/target/debug/build/test_multiple_modules-5f8b67dbd14af24f/out/errors.rs:1:1
  |
1 | //! Public errors.
  | ^^^^^^^^^^^^^^^^^^
  |
  = note: inner doc comments like this (starting with `//!` or `/*!`) can only appear before items
help: you might have meant to write a regular comment
  |
1 - //! Public errors.
1 + // Public errors.
  |

error[E0753]: expected outer doc comment
 --> /home/rafa/work/tighterror/target/debug/build/test_multiple_modules-5f8b67dbd14af24f/out/internal_errors.rs:1:1
  |
1 | //! Internal errors.
  | ^^^^^^^^^^^^^^^^^^^^
  |
  = note: inner doc comments like this (starting with `//!` or `/*!`) can only appear before items
help: you might have meant to write a regular comment
  |
1 - //! Internal errors.
1 + // Internal errors.
  |

For more information about this error, try `rustc --explain E0753`.
error: could not compile `test_multiple_modules` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.