tb: fix `clippy::needless_lifetimes` warning
Appeared since the release of v1.83.0-beta.1:

error: the following explicit lifetimes could be elided: 'a
   --> crates/tighterror-build/src/errors.rs:400:10
    |
400 |     impl<'a> core::fmt::Debug for Ident<'a> {
    |          ^^                             ^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
note: the lint level is defined here
   --> crates/tighterror-build/src/lib.rs:122:9
    |
122 | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(clippy::needless_lifetimes)]` implied by `#[deny(warnings)]`
help: elide the lifetimes
    |
400 -     impl<'a> core::fmt::Debug for Ident<'a> {
400 +     impl core::fmt::Debug for Ident<'_> {
    |

error: could not compile `tighterror-build` (lib) due to 1 previous error