tighterror: docs: remove usage of `class=warning` on paragraphs
On docs.rs they are rendered differently compared to the local build.
Removing because they look like a "hazard" warning.